### ISSUE TITLE
Allow underscores in addition to hyphens in URIs

### ISSUE THREAD

**Issue by scadams** [rackerlabs/riss#111]
https://github.com/rackerlabs/riss/blob/master/resource-design/uri-design.md

The mentioned page has the following standard:

`5. Use hyphens rather than spaces or underlines.  /configuration-boms`

I suggest allowing underscores to represent spaces in URIs and using hyphens to denote compound words since they have actual semantic meaning.

**Comment by benvolioT** [comment]
Here are a couple of counter arguments. These links come directly from the top-ten search results of a [google query for "underscore vs hyphen in url"](https://www.google.com/webhp?sourceid=chrome-instant&ion=1&espv=2&ie=UTF-8#q=underscore%20vs%20hyphen%20in%20url)

*  [seo basics hyphen or underscore for seo urls](http://www.ecreativeim.com/blog/2011/03/seo-basics-hyphen-or-underscore-for-seo-urls/): has a good explanation of why google recommends hyphen rather than underscore as a word separator. Google has always treated a dash as a word separator and an underscore as part of the word. From the google search engineer who explains it in a vido on that page: "now in practical terms, it doesn't make a very big difference...there are higher impact projects to work on \[than worrying about this issue\]"

*  [Google's guide to 'Keep a simple URL structure'](https://support.google.com/webmasters/answer/76329?hl=en): "We recommend that you use hyphens (-) instead of underscores (_) in your URLs."

*  [Google & Bing (Still) Handle Underscores & Dashes Differently](http://searchengineland.com/google-bing-handle-underscores-dashes-differently-89672): "A Bing spokesperson confirmed this for us via email today: 'We do not differentiate between dash and underscore in our URL ranking features.'"

These are all very SEO specific. If we issue the same query but ignore web pages with 'SEO' content, we get [these results](https://www.google.com/webhp?sourceid=chrome-instant&ion=1&espv=2&ie=UTF-8#q=underscore+vs+hyphen+in+url+-SEO): 

*  [The underscore is traditionally considered a word character by the w regex operator.](http://www.regular-expressions.info/charclass.html)

*  [Of Spaces, Underscores and Dashes](http://blog.codinghorror.com/of-spaces-underscores-and-dashes/): "Like NutraSweet and Splenda, neither is really an acceptable substitute for a space, but we might as well follow the established convention instead of inventing our own. That's how we ended up with the backslash as a path separator."

*  [Dashes Vs Underscores In URLs](http://haacked.com/archive/2007/03/15/dashes-vs-underscores-in-urls.aspx/): "The question is, does this still apply today? Does iteven \[sic\] matter? To be on the safe side, I'm falling in line for now. Or rather, in dash."

To me the most salient advice is this one from a [quora answer](https://www.quora.com/When-designing-URLs-for-a-REST-API-does-choosing-between-underscores-or-dashes-as-word-separators-matter"): "In theory it shouldn't matter.  According to strict RESTful design principles, other than the base URL/URI, the other URIs should really be opaque.  The client should learn about components through metadata.  This allows the underlying design structure to change in the future. Having said that, in practice, people do construct static URLs.  The most important thing is to make your API consistent.  Choose a convention and stick with it."

This is the advice I agree with. The two choices are almost equally valid. Google's SEO decision and its basis in Regex functionality cause us to call for using a dash rather than an underscore.  Let's be consistent.

That said, **I am open to changing this from a standard (i.e. a MUST do) to a recommendation (i.e. a SHOULD do).**

**Comment by scadams** [comment]
Thanks, @benvolioT.

I would agree that the standard should change from a MUST to a SHOULD for the following reasons:

1. Our internal projects don't concern themselves with SEO, so that isn't an issue for us.
2. Even with SEO, Google makes a very soft recommendation to use hyphens in URIs instead of underscores for very old-school reasoning. Google admits that there is not strong reasoning for it moving forward and that the only reason they haven't made the change is because they don't consider it to be a pressing issue, and that webmasters don't need to specifically switch to using hyphens if they have chosen underscores. Additionally, other searches engines don't even make the distinction. But again, this doesn't matter for our internal projects that don't care about SEO.
3. I think the reasoning that regexes treat underscores as a word character is the strongest reason here and most relevant to our purposes when developing internal systems, so I would agree that is a point in favor of preferring hyphens to underscores.
4. The semantic difference is the most compelling reason for distinguishing between hyphens and underscores. Sites that are concerned about semantic differences, notably Wikipedia, use underscores to represent spaces and dashes to represent compound words. We went with this approach for Global Search since the semantic difference can actually be meaningful for URI search query parameters. To save some time bringing forward the entire argument, this article discusses the reasoning: http://fletcher.tomalty.com/posts/2011/dashes_vs_underscores_in_urls/ (although SEO is a partial consideration in the article, which we are not concerned with). This semantic difference can also potentially help ambiguity with tags, which is a common use-case, though I doubt it would ever be much of an issue.

So, because there isn't very strong reasoning to choose one over the other, and there is reasoning to choose one or the other depending on the goals for the project, I would argue that internal project consistency is more important than cross-product consistency for this specific case, and that developers should be able to exercise judgement and choose what they think is best for what they are developing.

**Comment by benvolioT** [comment]
@scadams well articulated and great points. I have no problem switching this from a standard to a guideline.  I will loop in other project members in case they care. Feel free to create a pull request to fix this, or we can get to it as time allows.

**Comment by scadams** [comment]
I can submit a PR, but I don't see how to make the distinction between a MUST and a SHOULD. Is it just moving it from a standard to a guideline?

**Comment by scadams** [comment]
https://github.com/rackerlabs/riss/pull/112

**Comment by benvolioT** [comment]
Fixed by https://github.com/rackerlabs/riss/pull/112.

**Comment by benvolioT** [comment]
Hey @scadams - can you please close this github issue? I tried following [this advice](http://stackoverflow.com/a/26835572/87696), but it doesn't seem to have worked.  [Here is what we'd normally do to close the issue](https://help.github.com/articles/closing-issues-via-commit-messages/).

**Comment by scadams** [comment]
Looks like that's because my commit message would have needed the text, so I'm just closing this issue manually.
